export function DetailRow({ label, value, emphasize }) {
  return (
    <div className="flex items-center justify-between py-1.5">
      <span className="text-sm text-muted">{label}</span>
      <span className={emphasize ? "text-lg font-extrabold" : "text-sm font-semibold"}>{value}</span>
    </div>
  );
}

/** A bordered "document" card used for receipts & bills (also the print target). */
export function ReceiptDoc({ title, subtitle, children }) {
  return (
    <div className="card p-5 print:shadow-none">
      <p className="font-semibold">{title}</p>
      {subtitle && <p className="text-xs text-muted mb-2">{subtitle}</p>}
      {children}
      <div className="border-t border-line mt-3 pt-3 text-[11px] text-muted">Generated by Yolo-Home's</div>
    </div>
  );
}
